#!/bin/sh
set -e

echo "Setting up repository git configuration for GitHub..."
git config user.name "Ivan Pizhenko"
git config user.email "IvanPizhenko@users.noreply.github.com"
git config apply.whitespace fix

echo "Operation completed."
date
