#!/bin/sh
set -e

echo "Setting up repository git configuration for BitBucket..."
git config user.name "Ivan Pizhenko"
git config user.email "IvanPizhenko@users.noreply.bitbucket.org"
git config apply.whitespace fix

echo "Operation completed"
date
